### ISSUE TITLE
Field Wizard revamp

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-for-wordpress#114]
The JavaScript for the Field Wizards could benefit from a total rewrite.

- [ ] Refactor using Mithril.js
- [ ] Replace field if it's existing in form code #44 
- [ ] Add option for varying field widths #39
- [ ] Add advanced section with options like class, tabindex, pattern, etc.
- [ ] Split up address fields #38
